import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const PHONE = '27787214877'; // Public telephone number from agency's Google Maps listing. Confirm before launch.
const MAP_URL = 'https://maps.app.goo.gl/9ASD6kPaA4igmnyh7';
const IMG = {
  hero: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=2400&q=85',
  cape: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1000&q=85',
  coast: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=85',
  safari: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1000&q=85',
  detail: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1500&q=85',
};

function goTo(id) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); }
const wa = (msg) => `https://wa.me/${PHONE}?text=${encodeURIComponent(msg)}`;
const defaultMessage = 'Hello Gee Travel Agency, I would like help planning a trip.';

function Header({ onEnquire, openLegal }) {
  const [menu, setMenu] = useState(false);
  const jump = (id) => { setMenu(false); goTo(id); };
  return <header className="site-header"><div className="header-inner container">
    <button className="brand" onClick={() => jump('top')} aria-label="Gee Travel Agency, home"><span className="brand-mark">G<span className="brand-dot">.</span></span><span className="brand-text">GEE <small>TRAVEL AGENCY</small></span></button>
    <nav className={menu ? 'nav open' : 'nav'} aria-label="Main navigation"><button onClick={() => jump('explore')}>Explore</button><button onClick={() => jump('approach')}>Our approach</button><button onClick={() => jump('about')}>About</button><button onClick={() => jump('contact')}>Contact</button><button className="mobile-enquire" onClick={() => {setMenu(false); onEnquire();}}>Plan your trip</button></nav>
    <button className="header-cta" onClick={onEnquire}>Start planning <span aria-hidden="true">↗</span></button>
    <button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}><span/><span/></button>
  </div></header>;
}

const inspiration = [
  {number:'01', country:'SOUTH AFRICA', title:'The city & the coast', subtitle:'Cape Town', image:IMG.cape, desc:'City energy, mountain views, and the open ocean.'},
  {number:'02', country:'ISLAND ESCAPES', title:'A slower kind of day', subtitle:'Beach getaways', image:IMG.coast, desc:'Long afternoons, warm sand, and nowhere else to be.'},
  {number:'03', country:'AFRICAN ADVENTURES', title:'Into the extraordinary', subtitle:'Safari inspiration', image:IMG.safari, desc:'Wide-open landscapes and unforgettable encounters.'},
];
function App(){
  const [modal,setModal]=useState(false);
  const [legal,setLegal]=useState(null);
  const [form,setForm]=useState({name:'',destination:'',dates:'',travellers:'2',budget:'',notes:''});
  const [error,setError]=useState('');
  const update=(k,v)=>setForm(x=>({...x,[k]:v}));
  useEffect(()=>{document.body.style.overflow=modal||legal?'hidden':'';return()=>document.body.style.overflow='';},[modal,legal]);
  useEffect(()=>{const key=e=>{if(e.key==='Escape'){setModal(false);setLegal(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const submit=(e)=>{e.preventDefault();if(form.name.trim().length<2 || !form.destination.trim()){setError('Please add your name and where you would like to go.');return;}setError('');const message=`Hello Gee Travel Agency, I would like to enquire about a trip.\n\nName: ${form.name.trim()}\nDestination: ${form.destination.trim()}\nDates: ${form.dates||'Flexible'}\nTravellers: ${form.travellers||'Not specified'}\nBudget: ${form.budget||'Not specified'}\nNotes: ${form.notes||'None'}\n\nPlease let me know what options are available.`;window.open(wa(message),'_blank','noopener,noreferrer');};
  return <div id="top">
    <Header onEnquire={()=>setModal(true)} />
    <main>
      <section className="hero" aria-label="Discover travel"><img className="hero-image" src={IMG.hero} alt="Golden evening light over a vast mountain landscape" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow light">MAHIKENG, SOUTH AFRICA <span className="eyebrow-rule"/> YOUR JOURNEY STARTS HERE</p><h1>Go somewhere<br/><em>remarkable.</em></h1><p className="hero-description">The places you dream about are closer than you think. Tell us where you want to go, and let's start the conversation.</p><button className="button button-cream" onClick={()=>setModal(true)}>Let's plan your trip <span>↗</span></button></div><div className="hero-bottom"><span>GEE TRAVEL AGENCY</span><span>01 / THE WORLD AWAITS</span><button onClick={()=>goTo('explore')} aria-label="Scroll to destinations">SCROLL TO EXPLORE <span>↓</span></button></div></div></section>
      <section className="intro-section"><div className="container intro-grid"><p className="section-label">A JOURNEY WORTH TAKING <span className="tiny-rule"/></p><div><h2>There is more out there.<br/><em>Go and see it.</em></h2><p>Some journeys are about discovering somewhere new. Others are about getting away from it all. Whatever brings you here, let's find a way to make the journey yours.</p></div></div></section>
      <section className="explore-section" id="explore"><div className="container"><div className="section-heading"><div><p className="section-label">01 / FIND YOUR INSPIRATION</p><h2>The world is <em>waiting.</em></h2></div><p>Not sure where to begin? A few places and possibilities to get you thinking.</p></div><div className="destination-grid">{inspiration.map((d,i)=><article className="destination" key={d.number}><div className="destination-image"><img src={d.image} alt={`${d.subtitle} travel inspiration`} loading="lazy"/><span className="photo-number">{d.number} / 03</span></div><div className="destination-content"><div><p className="destination-category">{d.country}</p><h3>{d.title}</h3><p className="destination-subtitle">{d.desc}</p></div><button className="round-link" aria-label={`Enquire about ${d.subtitle}`} onClick={()=>{update('destination',d.subtitle);setModal(true);}}>↗</button></div></article>)}</div><p className="fine-print">Destinations shown for inspiration only. Availability, services, and prices must be confirmed directly with Gee Travel Agency.</p></div></section>
      <section className="statement-section" id="approach"><div className="statement-image"><img src={IMG.detail} alt="A quiet mountain valley and lake" loading="lazy"/></div><div className="statement-panel"><p className="section-label">02 / MADE FOR THE JOURNEY</p><h2>Less wondering.<br/><em>More wandering.</em></h2><p>Planning a trip should feel like the beginning of something exciting. Share your ideas, preferred dates and budget in one enquiry, and get the conversation moving.</p><div className="approach-steps"><div><span>01</span><strong>Tell us your plans</strong><p>Your destination, dates, and the people coming along.</p></div><div><span>02</span><strong>Start the conversation</strong><p>Send your details directly to the agency on WhatsApp.</p></div><div><span>03</span><strong>Explore your options</strong><p>Confirm available services and travel arrangements with the team.</p></div></div><button className="text-cta" onClick={()=>setModal(true)}>Send a travel enquiry <span>↗</span></button></div></section>
      <section className="about-section" id="about"><div className="container about-grid"><div><p className="section-label">03 / LOCAL ROOTS, BIG HORIZONS</p><h2>From Mahikeng<br/><em>to wherever's next.</em></h2></div><div className="about-copy"><p>Gee Travel Agency is listed in Dihatswane, Mahikeng, North West. This preview brings the agency online with a simple way for travellers to start an enquiry.</p><p>Whether you're travelling close to home or dreaming further afield, the best place to begin is a conversation.</p><button className="button button-dark" onClick={()=>setModal(true)}>Make an enquiry <span>↗</span></button></div></div></section>
      <section className="contact-section" id="contact"><div className="container contact-grid"><div><p className="section-label light">04 / LET'S GET GOING</p><h2>Your next story<br/><em>starts here.</em></h2><button className="button button-cream" onClick={()=>setModal(true)}>Plan your trip <span>↗</span></button></div><div className="contact-details"><p>GET IN TOUCH</p><a href={`tel:+${PHONE}`}>+27 78 721 4877</a><a href={wa(defaultMessage)} target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><p className="contact-subheading">FIND US</p><a href={MAP_URL} target="_blank" rel="noopener noreferrer">Dihatswane Village West<br/>Mahikeng, North West, South Africa ↗</a></div></div></section>
    </main>
    <footer className="footer"><div className="container footer-top"><div className="footer-brand"><span className="brand-mark">G<span className="brand-dot">.</span></span><span>GEE TRAVEL AGENCY</span></div><p>GO SOMEWHERE REMARKABLE.</p></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Gee Travel Agency. Website concept, pending business approval.</span><div><button onClick={()=>setLegal('privacy')}>Privacy</button><button onClick={()=>setLegal('terms')}>Terms</button><a href={MAP_URL} target="_blank" rel="noopener noreferrer">Location</a></div></div><div className="container demo-credit">Concept website by <a href="https://codevenient.co.za/" target="_blank" rel="noopener noreferrer">Codevenient Consulting</a>. Not an official booking platform.</div></footer>
    {modal&&<div className="overlay" onMouseDown={(e)=>{if(e.target===e.currentTarget)setModal(false)}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><div className="dialog-top"><p className="section-label">TRAVEL ENQUIRY</p><button className="close" onClick={()=>setModal(false)} aria-label="Close enquiry">×</button></div><h2 id="enquiry-title">Let's make <em>plans.</em></h2><p className="dialog-lead">A few details are all we need to get started. This form opens WhatsApp with your enquiry. No payment is taken.</p><form onSubmit={submit}><div className="field-row"><label>Your name <span>*</span><input value={form.name} onChange={e=>update('name',e.target.value)} maxLength={80} placeholder="Your full name" required/></label><label>Where to? <span>*</span><input value={form.destination} onChange={e=>update('destination',e.target.value)} maxLength={100} placeholder="Destination or open to ideas" required/></label></div><div className="field-row"><label>Preferred dates<input value={form.dates} onChange={e=>update('dates',e.target.value)} maxLength={100} placeholder="e.g. December, flexible"/></label><label>Travellers<input type="number" min="1" max="30" value={form.travellers} onChange={e=>update('travellers',e.target.value)}/></label></div><label>Approximate budget (optional)<input value={form.budget} onChange={e=>update('budget',e.target.value)} maxLength={80} placeholder="e.g. R15 000 total"/></label><label>Anything else?<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} maxLength={650} rows="3" placeholder="What would make this trip special?"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-dark submit" type="submit">Continue to WhatsApp <span>↗</span></button><p className="form-footnote">Your details are only shared when you choose to send the prepared WhatsApp message. WhatsApp's own privacy terms apply.</p></form></section></div>}
    {legal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setLegal(null)}}><section className="dialog legal-dialog" role="dialog" aria-modal="true" aria-labelledby="legal-title"><div className="dialog-top"><p className="section-label">WEBSITE INFORMATION</p><button className="close" onClick={()=>setLegal(null)} aria-label="Close">×</button></div>{legal==='privacy'?<><h2 id="legal-title">Privacy <em>notice.</em></h2><p className="legal-warning">DRAFT FOR CLIENT REVIEW — replace with the agency's approved POPIA-compliant policy before launch.</p><p>This demonstration website does not operate user accounts or store travel enquiries in a website database. The enquiry form prepares a WhatsApp message on your device. Your details are sent to the travel agency only if you choose to send the message through WhatsApp.</p><p>Contact requests may include your name, destination, approximate budget, travel dates and other details you supply. WhatsApp processes messages under its own terms and privacy policy.</p><p>Third-party images and external services may process basic usage information. The agency must confirm its data controller details, retention periods, lawful basis, rights request process and any analytics/cookies before publication.</p><p>Contact the agency using the publicly listed phone number for privacy enquiries.</p></>:<><h2 id="legal-title">Terms of <em>use.</em></h2><p className="legal-warning">DRAFT FOR CLIENT REVIEW — not final business terms or booking conditions.</p><p>This website is a design concept. Content and destinations are illustrative and do not represent confirmed travel products, package inclusions, live availability or prices.</p><p>Submitting an enquiry does not create a booking, guarantee availability, or establish a payment obligation. Any services, prices, cancellation terms, refund policies, travel documentation requirements and applicable supplier terms must be confirmed directly by the agency.</p><p>Site content is provided for general information. The agency must approve final terms, service descriptions, contact details and relevant legal disclosures before a public launch.</p></>}</section></div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
